# Generated by Django 5.0.9 on 2025-04-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/djretqgrx/image/upload/v1743987594/player_default_qmzlls.jpg', null=True, upload_to='players/', verbose_name='Foto del jugador'),
        ),
    ]
