# Generated by Django 5.0.9 on 2025-03-29 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=0, editable=False, verbose_name='Jornada')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('score_home', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Goles de equipo local')),
                ('score_away', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Goles de equipo visitante')),
                ('state', models.CharField(choices=[('WAITING', 'Pendiente'), ('IN_PROGRESS', 'En curso'), ('COMPLETED', 'Completado')], default='WAITING', max_length=20, verbose_name='Estado')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.club', verbose_name='Equipo visitante')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.club', verbose_name='Equipo local')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='PlayerParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_players', to='tournaments.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'verbose_name': 'Jugador en partido',
                'verbose_name_plural': 'Jugadores en partidos',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('LEAGUE', 'Liga'), ('CUP', 'Copa'), ('FRIENDLY', 'Amistoso'), ('OTHER', 'Otro')], default='OTHER', max_length=10, verbose_name='Tipo')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('photo', models.ImageField(blank=True, default='tournaments/torneo_default.png', null=True, upload_to='tournaments/', verbose_name='Foto del torneo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='tournaments_name_edd2ee_idx')],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament', verbose_name='Torneo'),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.PositiveIntegerField(default=1, editable=False, verbose_name='Jornadas')),
                ('points_system', models.JSONField(default=dict)),
                ('league_format', models.CharField(choices=[('SINGLE', 'Solo ida'), ('DOUBLE', 'Ida y vuelta')], default='SINGLE', max_length=10, verbose_name='Formato de liga')),
                ('teams_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Cantidad de equipos')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='tournaments.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Torneo Liga',
                'verbose_name_plural': 'Torneos Ligas',
            },
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', models.PositiveIntegerField(default=1, verbose_name='Rondas')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cup', to='tournaments.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Torneo Copa',
                'verbose_name_plural': 'Torneos Copas',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='core.club', verbose_name='Club')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'unique_together': {('tournament', 'club')},
            },
        ),
    ]
