# Generated by Django 5.0.9 on 2025-04-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='photo',
            field=models.ImageField(blank=True, default='tournaments/tournament_default.jpg', null=True, upload_to='tournaments/', verbose_name='Foto del torneo'),
        ),
    ]
