# Generated by Django 5.0.9 on 2025-04-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='photo',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/djretqgrx/image/upload/v1743987668/tournament_default_ramb9s.jpg', null=True, upload_to='tournaments/', verbose_name='Foto del torneo'),
        ),
    ]
