# Generated by Django 5.0.9 on 2025-03-29 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_wins', models.PositiveIntegerField(default=0, verbose_name='Partidos ganados')),
                ('total_losses', models.PositiveIntegerField(default=0, verbose_name='Partidos perdidos')),
                ('total_draws', models.PositiveIntegerField(default=0, verbose_name='Partidos empatados')),
                ('goals_scored', models.PositiveIntegerField(default=0, verbose_name='Goles marcados')),
                ('goals_conceded', models.PositiveIntegerField(default=0, verbose_name='Goles recibidos')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='tournaments.participation', verbose_name='Participación de club en torneo')),
            ],
            options={
                'verbose_name': 'Estadisticas de Club',
                'verbose_name_plural': 'Estadisticas de Clubes',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_scored', models.PositiveIntegerField(default=0, verbose_name='Goles marcados')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Asistencias')),
                ('shots_on_target', models.PositiveIntegerField(default=0, verbose_name='Tiros al arco')),
                ('completed_passes', models.PositiveIntegerField(default=0, verbose_name='Pases completados')),
                ('duel_wins', models.PositiveIntegerField(default=0, verbose_name='Duelos ganados')),
                ('ball_recoveries', models.PositiveIntegerField(default=0, verbose_name='Recuperaciones de balon')),
                ('blocks', models.PositiveIntegerField(default=0, verbose_name='Bloqueos')),
                ('fouls_drawn', models.PositiveIntegerField(default=0, verbose_name='Faltas recibidas')),
                ('fouls_committed', models.PositiveIntegerField(default=0, verbose_name='Faltas cometidas')),
                ('yellow_cards', models.PositiveIntegerField(default=0, verbose_name='Tarjetas amarillas')),
                ('red_cards', models.PositiveIntegerField(default=0, verbose_name='Tarjetas rojas')),
                ('saves', models.PositiveIntegerField(default=0, verbose_name='Atajadas')),
                ('player_participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='tournaments.playerparticipation', verbose_name='Participacion de jugador en partido')),
            ],
            options={
                'verbose_name': 'Estadísticas de Jugador',
                'verbose_name_plural': 'Estadísticas de Jugadores',
            },
        ),
    ]
